### ISSUE TITLE
QRT does not appear when embedding

### ISSUE THREAD

**Issue by Apocolypto** [FixTweet/FxTwitter#1005]
When trying to embed a tweet with a QRT of a tweet with a video, it only shows the text for the first tweet and fails to show the quoted text of the second tweet with video

Example: ![Screenshot_20241009_003009.png](https://github.com/user-attachments/assets/41b490a9-0a96-4d18-98dc-f205522ebaae)

Actual tweet: ![Screenshot_20241009_003433_Twitter.png](https://github.com/user-attachments/assets/fdab7e88-709b-4245-abe7-d0eeedb6e1e2)

Link to example tweet: https://x.com/Delby___/status/1843684531347567091?s=19

**Comment by dangeredwolf** [comment]
Can't fix on Discord because of the limitations they put on the way videos are embedded. Work on Telegram etc.

**Comment by Apocolypto** [comment]
How come vxtwitter's implementation works then? It should be possible.
![Screenshot_20241013_124510.png](https://github.com/user-attachments/assets/fdf8784b-30ce-4217-98d0-60c11f4f7683)

**Comment by Apocolypto** [comment]
> How come vxtwitter's implementation works then? It should be possible.
> ![Screenshot_20241013_124510.png](https://github.com/user-attachments/assets/fdf8784b-30ce-4217-98d0-60c11f4f7683)
> 
> 

Additionally, I do want to point out that fxtwitter does work when you quote a tweet with a video, see example attached below
![Screenshot_20241013_125009.png](https://github.com/user-attachments/assets/c01dab81-ded6-49db-90e7-92206e95bbdf)

Link to tweet: https://x.com/jadenarc/status/1845160317627555880
