### ISSUE TITLE
Video embeds sometimes not working in Telegram

### ISSUE THREAD

**Issue by rafitamolin** [FixTweet/FxTwitter#1020]
Videos/GIFs are sometimes embedded as files:

![](https://s.chollo.to/xSjhus.png)

You can test for yourself with these tweets:
- `https://fixupx.com/TheSillySnail/status/1847399773285786026`
- `https://fxtwitter.com/ihybratz/status/1847276121416499276`

**Comment by dangeredwolf** [comment]
I made a tweak that should work around this issue. Let me know if it's working now!

**Comment by adueppen** [comment]
Here's another tweet where it happens, worth noting too that using Webpage Bot doesn't fix the situation. https://fxtwitter.com/fatherstink/status/1847411896376283248

**Comment by dangeredwolf** [comment]
@adueppen Weird, the one you sent me literally works o.O
<img width="476" alt="Screenshot 2024-10-19 at 08 03 37" src="https://github.com/user-attachments/assets/d3f5b28a-55c9-480d-a471-2f91b0f7db2d">

**Comment by rafitamolin** [comment]
It's working fine now, thank you very much!
