### ISSUE TITLE
[FxBsky] Multi-image post that also contains a quoted image - "Crash" on Telegram, QRT-only on Discord

### ISSUE THREAD

**Issue by HeyItsLollie** [FixTweet/FxTwitter#1026]
I attempted to link a Bluesky post that contains two images, and which also quotes another post containing a image. The preview completely broke on Telegram, and embedded incomplete on Discord.

The post in question: A full-page advert for Gex 3 on PS1, in which Gex's live-action female sidekick poses topless with her chest covered by Gex's hands. This references a Rolling Stone magazine cover featuring Janet Jackson in the same pose.
https://fxbsky.app/profile/iznaut.com/post/3l72saerk742v

Telegram only displays a (truncated) crash message. I've attempted using Telegram's "Webpage Bot" (https://t.me/WebpageBot) to refresh the cached link in case this was just a temporary issue, but I've had no success.
![firefox - 2024-10-22 - 11-28-29](https://github.com/user-attachments/assets/f401b384-5797-4351-bedd-10cd45ad2fa1)

Discord embeds, but only displays the image in the quoted post.
![Discord - 2024-10-22 - 11-30-04](https://github.com/user-attachments/assets/8ff1399f-133a-437a-a041-3876894a27b5)

Finally, the post as it appears on Bluesky:
![firefox - 2024-10-22 - 11-23-31](https://github.com/user-attachments/assets/ecc830d5-b1d8-45e5-b4e2-adbb9df37b09)

**Comment by dangeredwolf** [comment]
Should be fixed now!

**Comment by HeyItsLollie** [comment]
That fixed the crash message, thank you!

While I'm here, is there a way to display the linked post's images, rather than the quoted post? I haven't been able to force it with d.fx or g.fx
