### ISSUE TITLE
[FxBsky] Video Endpoint

### ISSUE THREAD

**Issue by SomewhatDamaged** [FixTweet/FxTwitter#1027]
Noticed there isn't support for this yet, and your feed said they didn't know how to get an MP4 file, so...

`https://bsky.social/xrpc/com.atproto.sync.getBlob?did=AUTHOR_DID&cid=VIDEO_ID`

This will get you an MP4 vid. Discord relies on file extensions, though, so you'll need to throw `<meta property="og:video:type" content="video/mp4">` into the Opengraph to get it to embed.

**Comment by dangeredwolf** [comment]
Implemented! https://github.com/FixTweet/FxTwitter/commit/fd539884d692c44aa87a21a063e57d7b277ff219
