### ISSUE TITLE
[FxBsky] Higher Quality Images

### ISSUE THREAD

**Issue by SomewhatDamaged** [FixTweet/FxTwitter#1028]
Bluesky serves JPEGs by default, which sucks.

You can provide the PNG version by changing the end of them.

`https://cdn.bsky.app/img/feed_fullsize/plain/<DID>/<REF>@jpeg`
to
`https://cdn.bsky.app/img/feed_fullsize/plain/<DID>/<REF>@png`

**Comment by Gilgames32** [comment]
the extension after the `@` doesnt change anything unfortunately, its merely a format suggestion for the file to be saved in

bluesky compresses everything by default, all of the images are stored as `.jpg` (you can test this by removing the `@jpeg` completely)

yes, putting `@png` will result in a `.png` file but if you zoom you can see that the image is still compressed, though not as much as on twitter, but its not lossless

**Comment by dangeredwolf** [comment]
Yeah I did not notice a meaningful quality difference especially since bsky.app only uses the jpeg versions.
