### ISSUE TITLE
Cloudflare Deployment API issue

### ISSUE THREAD

**Issue by BrokedTV** [FixTweet/FxTwitter#1071]
Hey!
I decided to deploy my own FxTwitter to not put load on fxtwitter.com and for spike usages, i deployed it successfully and tweets ger redirected however if i try to use the API
api.mydomain.com/username/status/id

i get the following SSL error
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

and i haven't been able to understand how to fix it. 
Thanks

**Comment by BrokedTV** [comment]
My bad, it was an issue at the original domain register, wasted 2 days on it

**Comment by dangeredwolf** [comment]
Glad you figured it out :D
