### ISSUE TITLE
Tweet stats broken

### ISSUE THREAD

**Issue by Apocolypto** [FixTweet/FxTwitter#1080]
Tweet stats appear to be broken, screenshots are attached down below.

Before: 
![image](https://github.com/user-attachments/assets/df8924e7-0841-4af3-bdab-ec2dccbd707d)

After:
![image](https://github.com/user-attachments/assets/c7a2949d-de62-497f-a44d-f0d78932b8ba)

**Comment by dangeredwolf** [comment]
Thanks for reporting this! I accidentally introduced a bug while merging an old pull request of mine, it should be fixed now.
