### ISSUE TITLE
Links are not working

### ISSUE THREAD

**Issue by sallyFoster** [FixTweet/FxTwitter#1107]
Links are giving an error saying that the post doesn't exist

![image](https://github.com/user-attachments/assets/8514f54f-2535-4260-ad4c-a8089d09e59c)

**Comment by dangeredwolf** [comment]
Try it again, I accidentally broke something when I pushed an update on a plane <.< 

Add a query string (like ?asdf) to invalidate the cache

**Comment by dangeredwolf** [comment]
You can check the current uptime status at https://status.fxtwitter.com

**Comment by dangeredwolf** [comment]
Sorry, something else broke, can you try it again and tell me if it works better now?

**Comment by Gestrid** [comment]
> Try it again, I accidentally broke something when I pushed an update on a plane <.<

I don't know if it takes a bit to update, but it doesn't seem to be fixed yet.

**Comment by sallyFoster** [comment]
It is working now. Even though it takes like 5 seconds to pop up the embed after sending the link.
