### ISSUE TITLE
Replying to @[object Object]

### ISSUE THREAD

**Issue by TamimplayzDev** [FixTweet/FxTwitter#467]
The original tweets author name in replies is displayed as “@[object Object]”

![FxTwitter](https://github.com/FixTweet/FixTweet/assets/74967194/a9188dc6-6955-4577-b0a2-e8b1008b1676)
![FixUpX](https://github.com/FixTweet/FixTweet/assets/74967194/d12aab7a-21c9-4d4b-b735-a1339c1e8bec)
![Twittpr](https://github.com/FixTweet/FixTweet/assets/74967194/d8146de4-9775-417a-9c93-43580116213b)

**Comment by dangeredwolf** [comment]
My bad, this got borked by some internal changes made to how the API works and I didn't notice it until now. Should be fixed no!
