### ISSUE TITLE
Custom Formatting On Embeds

### ISSUE THREAD

**Issue by theblakelalonde** [FixTweet/FxTwitter#544]
There are instances where I find the embeds feel cluttered or that the information being displayed is seemingly in the wrong position.
I'm wondering if there was a way to append a number to the query string in the URL that would change the formatting of the embed.  Of course, you'd have to set up these different formats yourself and identify them to us.

Personally, I'd love to see the user's avatar and name in the footer of the embed, and remove the stats from the top (comments, likes, respots, views...).

**Comment by dangeredwolf** [comment]
As nice as a lot of those things would be, we work within the confines of website embeds which don't offer us nearly that level of flexibility.

**Comment by theblakelalonde** [comment]
Is there possibly a way to scrape the data that is coming in from the `fxtwitter`'s embed/URL?

As in I have a personal discord bot that I use to delete the user's original message and replace the message with one from the bot with the new twitter link (twitter.com/....  turns to fxtwitter.com/...).  But I'd rather not show the link when the bot is sending its message, as well as there are something things that I'd like to personally rearrange on the embed. 

Is that data available at any point that I could access it and build a personal embed through the Discord embedBuilder?

**Comment by dangeredwolf** [comment]
Sorry I forgot to reply, but we do have a status fetch API that powers the underpinning of our embeds which you can use: https://github.com/FixTweet/FxTwitter/wiki/Status-Fetch-API
