### ISSUE TITLE
Instant View on Telegram Broken

### ISSUE THREAD

**Issue by TuxKick** [FixTweet/FxTwitter#574]
fx and fixupx on Telegram doesn't show any media on Telegram unless you add d. or g. to the beginning. Instant View is broken.

iOS 17.2
Telegram 10.4.1

**Comment by TuxKick** [comment]
I've determined it only is broken on links listed as sensitive media. Others seem fine.

**Comment by dangeredwolf** [comment]
At the moment, sensitive posts do work in Instant View for me. To help us narrow down the problem, could you please provide:
- An example Tweet where the issue occurs
- Information about which Telegram client you are using. For example, iOS, Android, Mac, Telegram Desktop, Unigram, etc.

**Comment by TuxKick** [comment]
**Warning, the below image/link is NSFW and contains partial nudity.**

https://fixupx.com/washlet_mskm/status/1738944540990722313?s=52&t=NSLOJXNT0GY7aWKwVzq9sA

This did not produce an instant view. Only way to produce a preview was with g.fixupx or g.fxtwitter

**Comment by dangeredwolf** [comment]
Thank you so much for this. I can reproduce the issue with that link.

**Comment by dangeredwolf** [comment]
![image](https://github.com/FixTweet/FixTweet/assets/2636265/0efa2fc7-8348-4e84-9a33-4af878a6dfc7)
Trying to debug it with Telegram's Instant View templates website and it is getting stuck on "Processing links...". That's bizarre, I didn't know that was something that could even happen.
