### ISSUE TITLE
Can't GET from api via code but can via browser

### ISSUE THREAD

**Issue by ALEKSEYR554** [FixTweet/FxTwitter#582]
My ruby code for this is very simple
```
require 'Faraday'
conn = Faraday::Connection.new 'https://api.fxtwitter.com/ALEKSEYR554_'
p conn.get
```
and everytime i get `SSL_connect returned=1 errno=0 peeraddr=104.21.87.14:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)` no matter what i do, **but opening api link from browser works**. GET from telegram bot api works with no problem. I tryed disabling ssl check when sending request, use firefox's cacert.pem nothing worked. And idk if it's problem from my side or server one bc I'm strugling with it for a week i guess. So maybe something went wrong with server, if not i'll look for solution

**Comment by dangeredwolf** [comment]
We're using Cloudflare if that helps at all. I'm not terribly familiar with Ruby or Faraday so I'm not sure if there's additional logging you can turn on and look at or if there are any known compatibility issues between Cloudflare's free SSL certs and Faraday.
