### ISSUE TITLE
Request: add Iframely user agent to list of UAs for embed generation

### ISSUE THREAD

**Issue by atomicthumbs** [FixTweet/FxTwitter#663]
Iframely is a link previewing/embedding service used by a variety of websites. The one I use that would benefit from this is Cohost, a blogging/social networking site. As-is, linking to a variety of posts on Twitter returns an error stating that the account's suspended, when it hasn't been. Using a BetterTwitFix URL attempts an embed but returns the same error.

According to [their documentation,](https://iframely.com/docs/about) their user agent is Iframely/1.3.1 (+https://iframely.com/docs/about) (with the version and name extension subject to change). I believe adding it to the list would enable preview generation.

This change [was recently implemented for BetterTwitFix](https://github.com/dylanpdx/BetterTwitFix/issues/190) and appears to work perfectly; it'd be nice to have it on FxTwitter as well.

**Comment by dangeredwolf** [comment]
Easy fix, let me know if it works OK now 👍
