### ISSUE TITLE
[Feature Request] Hide Media

### ISSUE THREAD

**Issue by barraIhsan** [FixTweet/FxTwitter#726]
sometimes, the image/media is not necessary and can clutter the chat. So is it possible to add like another subdomain/any other way that hide the media? Or at least show that there is a media, but the embed just doesn't load it

Example:
![image](https://github.com/FixTweet/FxTwitter/assets/57800056/7d50e96a-f594-452d-aa56-3873f0ed69e6)
![image](https://github.com/FixTweet/FxTwitter/assets/57800056/d699a597-14a9-4cee-846c-9222a4231ddb)
This one right here, the image/media is not really necessary. The only needed part is the caption.

**Comment by dangeredwolf** [comment]
I just realized it's not documented, but `t.fxtwitter.com` / `t.fixupx.com` should be exactly what you're looking for! I'll add it to the README

**Comment by barraIhsan** [comment]
> I just realized it's not documented, but `t.fxtwitter.com` / `t.fixupx.com` should be exactly what you're looking for! I'll add it to the README

oh, I'm sure some people are searching for that. Thanks!

**Comment by dangeredwolf** [comment]
I added it to the readme now!
