### ISSUE TITLE
Request: Add bluesky support to discord bot

### ISSUE THREAD

**Issue by cjshrader** [FixTweet/FxTwitter#757]
It'd be great if you could add support for bluesky. Functionality would be nearly identical. If someone posts a bluesky link (bsky.app), it reposts with the "fixed" link (bsyy.app). That fixed link is being maintained here: https://github.com/ThornbushHQ/FixBluesky

**Comment by Invertex** [comment]
This issue should be closable now that it has support?

**Comment by cjshrader** [comment]
No complaints from me
