### ISSUE TITLE
Prevent redirection to x.com from fxtwitter

### ISSUE THREAD

**Issue by elijahr2411** [FixTweet/FxTwitter#822]
When someone clicks an fxtwitter link, `?mx=1` should be added to the twitter URL it redirects to, which prevents the redirect to x.com

Example:

twitter.com/someone/status/1234567890 -> might redirect to x.com
twitter.com/someone/status/1234567890?mx=1 -> Will stay on twitter.com, at least for now

**Comment by joshcangit** [comment]
If you haven't heard the news or the announcement, Twitter has already migrated, albeit not completely, to x.com so all those twitter.com links have multiple redirects, iirc, or the links become broken.

**Comment by KoolAidDogan** [comment]
It bugs out and plays tug of war between directories for me.

**Comment by AncientAzem** [comment]
Just wanted to make note on here that while the adding the `?mx=1` param to the redirect does keep it on twitter.com site, a user's login session does not work unless they are redirected onto the x.com version of the site. So if someone opened an fx link with the intent to interact with the post they now need to reload the page to do so.

**Comment by dangeredwolf** [comment]
Yeah, good point @AncientAzem. At the moment I'm leaning towards just not doing anything because either you can use an extension to prevent redirection to x.com, or for people already using x.com it works like normal as-is.
