### ISSUE TITLE
fxtwitter.com links on telegram lead to some crypto scam

### ISSUE THREAD

**Issue by MartynDerg** [FixTweet/FxTwitter#847]
see title. for some reason the embed goes to "fxall", a self proclaimed crypto trading platform that is probably a scam. DOESN'T happen when typing only fxtwitter.com though, that still dorects to the github. but embeds go to the crypto scam

**Comment by dangeredwolf** [comment]
I’m guessing this is due to telegram quirks where it sometimes generates an embed before you finish typing a URL. Do you have an example URL?

**Comment by Akulatraxas** [comment]
I encountered this today and found that fx dot com leads to exactly that crypto site, so probably an mistake while overwriting twitter with fx instead of prefixing it.
