### ISSUE TITLE
Translations stopped working

### ISSUE THREAD

**Issue by Dragan232** [FixTweet/FxTwitter#852]
Greetings, it appears the translation feature ceased to work.
![Screenshot_2024-06-18-18-23-09-249_com discord](https://github.com/FixTweet/FxTwitter/assets/153384359/79e3140a-0a62-4959-a536-b987ec2c4532)

**Comment by dangeredwolf** [comment]
For a while, what appeared to be a server side issue affected translations. It seems this has now been resolved. You can also track translation issues in #435

<img width="479" alt="Screenshot 2024-06-18 at 14 11 23" src="https://github.com/FixTweet/FxTwitter/assets/2636265/8130eeac-8d23-4b3a-9cd1-a85aa23715a2">

**Comment by entailz** [comment]
Translations are broken again, either that or the API is rate limited
