### ISSUE TITLE
Request: Newgrounds embed support

### ISSUE THREAD

**Issue by Thedeur** [FixTweet/FxTwitter#967]
Posting Newgrounds links in Discord only brings up a thumbnail of the image; it'd be nice to have a service that provides the actual image + stats. There doesn't seem to be anything that exists for Newgrounds yet, so asking here as a start.

**Comment by dangeredwolf** [comment]
This is an interesting idea but probably beyond the scope of this project. I personally don't use newgrounds myself so it'd probably be better to ask someone in that community to maintain something for it :)
